# New-Item -ItemType Junction -Path $env:PUBLIC\Documents\EMPRESS -Target "$HOME\Мой диск\документы\hardlinks\EMPRESS"
# New-Item -ItemType Junction -Path $env:PUBLIC\Documents\OnlineFix -Target "$HOME\Мой диск\документы\hardlinks\OnlineFix"
# New-Item -ItemType Junction -Path $env:PUBLIC\Documents\Steam\CODEX -Target "$HOME\Мой диск\документы\hardlinks\CODEX"
# New-Item -ItemType Junction -Path $HOME\Documents\PPSSPP -Target "$HOME\Мой диск\документы\hardlinks\PPSSPP"
# New-Item -ItemType Junction -Path "$env:APPDATA\Goldberg SteamEmu Saves" -Target "$HOME\Мой диск\документы\hardlinks\Goldberg SteamEmu Saves"
# New-Item -ItemType Junction -Path "$env:APPDATA\Ryujinx\bis\user\save" -Target "$HOME\Мой диск\документы\hardlinks\ryujinx"
# New-Item -ItemType Junction -Path "$HOME\scoop\persist\ryujinx-ava\portable\bis\user\save" -Target "$HOME\Мой диск\документы\hardlinks\ryujinx"
# New-Item -ItemType Junction -Path "$HOME\scoop\apps\yuzu-pineapple\current\user\nand\user\save" -Target "$HOME\Мой диск\документы\hardlinks\yuzu"
# New-Item -ItemType Junction -Path $env:ChocolateyToolsLocation\RPCS3\dev_hdd0\home\00000001\savedata -Target "$HOME\Мой диск\документы\hardlinks\rpcs3"
