#!/bin/bash

if grep "*.torrent" "$1"; then
  notify-send "Added $(basename "$1") to remote rTorrent"
  sftp server <<'END'
  put -f $1 media/torrents/watch
END
fi
if [[ $1 == magnet:* ]]; then
  notify-send "Added magnet link to remote rTorrent"
  [[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit;
  echo "d10:magnet-uri${#1}:${1}e" > "meta-${BASH_REMATCH[1]}.torrent"
  sftp server <<'END'
  put -f meta-${BASH_REMATCH[1]}.torrent media/torrents/watch
END
  rm "meta-${BASH_REMATCH[1]}.torrent"
fi
