#!/bin/bash

if grep "*.torrent" "$1"; then
  notify-send "Added $(basename "$1") to rTorrent"
  mv "$1" "$XDG_DATA_HOME/rtorrent/watch"
fi
if [[ $1 == magnet:* ]]; then
  notify-send "Added magnet link to rTorrent"
  cd "$XDG_DATA_HOME/rtorrent/watch" || exit 1
  [[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit;
  echo "d10:magnet-uri${#1}:${1}e" > "meta-${BASH_REMATCH[1]}.torrent"
fi
